#!/bin/bash

apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/3984565a/research ensure=absent force=true
puppet resource file /tmp/3984565a ensure=absent force=true
puppet resource file /tmp/3984565a ensure=directory
puppet resource file /tmp/3984565a/research ensure=directory
cd /tmp/3984565a/research
git clone https://github.com/HelloRave/3984565a_op_repo.git
cp -p /tmp/3984565a/research/3984565a_op_repo/3984565a_index.html /var/www/html