#!/bin/bash

puppet resource file /tmp/clone ensure=absent force=true;
puppet resource file /tmp/clone ensure=directory;
cd /tmp/clone;
git clone https://github.com/HelloRave/devops_repo.git;
targets=puppetclient1.localdomain;
locate_script='/tmp/clone/devops_repo/script_to_run';
bolt script run $locate_script -t $targets -u clientadm -p user123 --no-host-key-check --run-as root;

script_to_run

apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/clone ensure=absent force=true
puppet resource file /tmp/clone ensure=directory
cd /tmp/clone
git clone https://github.com/HelloRave/devops_repo.git
cp -p /tmp/clone/devops_repo/index.html /var/www/html
